insert into genders(name)
values ('male'),
       ('female'),
       ('others');

insert into cities(name, abbreviation)
values ('An Giang', 'AG'),
       ('Bà Rịa - Vũng Tàu', 'BRVT'),
       ('Bắc Giang', 'BG'),
       ('Bắc Kạn', 'BK'),
       ('Bạc Liêu', 'BL'),
       ('Bắc Ninh', 'BN'),
       ('Bến Tre', 'BT'),
       ('Bình Định', 'BĐ'),
       ('Bình Dương', 'BD'),
       ('Bình Phước', 'BP'),
       ('Bình Thuận', 'BTh'),
       ('Cà Mau', 'CM'),
       ('Cần Thơ', 'CT*'),
       ('Cao Bằng', 'CB'),
       ('Đà Nẵng', 'ĐN*'),
       ('Đắk Lắk', 'ĐL'),
       ('Đắk Nông', 'ĐN'),
       ('Điện Biên', 'ĐB'),
       ('Đồng Nai', 'ĐNai'),
       ('Đồng Tháp', 'ĐT'),
       ('Gia Lai', 'GL'),
       ('Hà Giang', 'HG'),
       ('Hà Nam', 'HN'),
       ('Hà Nội', 'HN*'),
       ('Hà Tĩnh', 'HT'),
       ('Hải Dương', 'HĐ'),
       ('Hải Phòng', 'HP*'),
       ('Hậu Giang', 'HGi'),
       ('Hoà Bình', 'HB'),
       ('Hưng Yên', 'HY'),
       ('Khánh Hòa', 'KH'),
       ('Kiên Giang', 'KG'),
       ('Kon Tum', 'KT'),
       ('Lai Châu', 'LC'),
       ('Lâm Đồng', 'LD'),
       ('Lạng Sơn', 'LS'),
       ('Lào Cai', 'LCai'),
       ('Long An', 'LA'),
       ('Nam Định', 'NĐi'),
       ('Nghệ An', 'NA'),
       ('Ninh Bình', 'NB'),
       ('Ninh Thuận', 'NT'),
       ('Phú Thọ', 'PT'),
       ('Phú Yên', 'PY'),
       ('Quảng Bình', 'QB'),
       ('Quảng Nam', 'QNam'),
       ('Quảng Ngãi', 'QNg'),
       ('Quảng Ninh', 'QN'),
       ('Quảng Trị', 'QT'),
       ('Sóc Trăng', 'ST'),
       ('Sơn La', 'SL'),
       ('Tây Ninh', 'TN'),
       ('Thái Bình', 'TB'),
       ('Thái Nguyên', 'TNg'),
       ('Thanh Hóa', 'TH'),
       ('Thừa Thiên Huế', 'TTH'),
       ('Tiền Giang', 'TG'),
       ('Thành phố Hồ Chí Minh', 'HCM*'),
       ('Trà Vinh', 'TV'),
       ('Tuyên Quang', 'TQ'),
       ('Vĩnh Long', 'VL'),
       ('Vĩnh Phúc', 'VP'),
       ('Yên Bái', 'YB');

insert into kol_fields(name)
values ('Làm Đẹp (Beauty)'),
       ('Ẩm Thực (Food)'),
       ('Du Lịch (Travel)'),
       ('Thể Thao (Sport)'),
       ('Đời Sống (Life Style)'),
       ('Thời Trang (Fashion)'),
       ('Sức Khoẻ (Health)'),
       ('Công Nghệ (Tech)'),
       ('Giải Trí (Entertainment)');

insert into kols (gender_id, city_id, kol_field_id,facebook_url, instagram_url, tiktok_url, youtube_url, user_id)
values (1, 14, 1, 'https://facebook.com/sangkol', 'https://instagram.com/sangkol', 'https://tiktok.com/sangkol', 'https://youtube.com/sangkol', 2),
       (2, 15, 2, 'https://facebook.com/huykol', 'https://instagram.com/huykol', 'https://tiktok.com/huykol', 'https://youtube.com/huykol', 3),
       (1, 16, 3, 'https://facebook.com/thangkol', 'https://instagram.com/thangkol', 'https://tiktok.com/thangkol', 'https://youtube.com/thangkol', 4),
       (2, 17, 4, 'https://facebook.com/chankol', 'https://instagram.com/chankol', 'https://tiktok.com/chankol', 'https://youtube.com/chankol', 5),
       (1, 18, 5, 'https://facebook.com/hieukol', 'https://instagram.com/hieukol', 'https://tiktok.com/hieukol', 'https://youtube.com/hieukol', 6);
