insert into campaigns(name, timestamp, start_time, finish_time, location, description, details, status, enterprise_id)
values ('Trải nghiệm sống trong căn hộ chung cư Đà Nẵng - Khám phá môi trường sống và dịch vụ cao cấp', '2023-05-20 07:20:60 +7:00','2023-05-10 10:00:00 +7:00','2023-05-20 12:00:00 +7:00','Chung cư Mường Thanh - Đà Nẵng','Chúng tôi đang tìm kiếm một KOL để trải nghiệm sống trong căn hộ chung cư tại Đà Nẵng trong vòng 2 tháng. Bạn sẽ có cơ hội khám phá môi trường sống, trải nghiệm các dịch vụ cao cấp và tham gia các hoạt động xã hội trong khu đô thị. Hãy cùng chúng tôi chia sẻ về điều kiện sống, tiện ích và các trải nghiệm độc đáo mà căn hộ chung cư tại Đà Nẵng mang lại.','1.Môi trường sống và điều kiện học tập: Bạn sẽ được trải nghiệm sống trong căn hộ chung cư tại Đà Nẵng và chia sẻ về môi trường sống, an ninh, tiện ích xung quanh như trường học, bệnh viện, công viên và cơ sở hạ tầng. Ngoài ra, hãy đánh giá điều kiện học tập cho các gia đình có trẻ em và cơ hội giáo dục tại khu vực này.\n2.Các khu vui chơi và giải trí: Trong thời gian ở Đà Nẵng, hãy khám phá các khu vui chơi, giải trí và các hoạt động ngoài trời như công viên, sân golf, bể bơi và phòng tập thể dục. Chia sẻ với cộng đồng về trải nghiệm của bạn và những hoạt động giải trí thú vị mà căn hộ chung cư tại Đà Nẵng mang lại.\n3.Dịch vụ sống và ăn uống: Đánh giá các dịch vụ sống cao cấp như bãi để xe, an ninh, quản lý tòa nhà và các dịch vụ hỗ trợ khác. Hãy chia sẻ về trải nghiệm của bạn về môi trường sống và chất lượng dịch vụ trong căn hộ chung cư. Ngoài ra, khám phá các địa điểm ẩm thực độc đáo và quán ăn nổi tiếng tại Đà Nẵng và chia sẻ với cộng đồng về trải nghiệm ẩm thực tại khu vực này.','COMPLETED',3),
       ('Hợp tác cùng KOL để quảng bá chủ đề Du lịch ẩm thực', '2023-05-20 07:20:60 +7:00','2023-05-10 10:00:00 +7:00','2023-05-20 12:00:00 +7:00','Hội An','Chúng tôi đang tìm kiếm một KOL (Key Opinion Leader - Người có ảnh hưởng và tác động trong lĩnh vực) đam mê du lịch ẩm thực, người có khả năng kết hợp tuyệt vời giữa trải nghiệm du lịch và ẩm thực để quảng bá cho chủ đề Du lịch ẩm thực của chúng tôi. Bạn sẽ có cơ hội khám phá những món ăn độc đáo, trải nghiệm văn hóa đa dạng và chia sẻ những hương vị tuyệt vời với cộng đồng trực tuyến của bạn.','Chúng tôi mong muốn hợp tác với một KOL đặc biệt, người có khả năng sáng tạo và năng động trong việc truyền tải thông điệp về du lịch ẩm thực. Bạn sẽ có nhiệm vụ thực hiện các nhiệm vụ sau đây:\n\n1.Khám phá: Bạn sẽ có cơ hội tham quan các điểm đến du lịch ẩm thực hàng đầu trên thế giới. Hãy khám phá những quán ăn địa phương, chợ địa phương, và trải nghiệm những món ăn độc đáo và truyền thống. Hãy đưa khán giả của bạn vào hành trình của bạn và chia sẻ những trải nghiệm tuyệt vời.\n2.Chia sẻ văn hóa: Hãy giới thiệu văn hóa địa phương và truyền thống ẩm thực của mỗi địa điểm du lịch. Tìm hiểu về nguồn gốc, cách nấu, và cảm nhận hương vị độc đáo của các món ăn. Chia sẻ câu chuyện và thông tin thú vị về lịch sử, phong tục và tập quán liên quan đến ẩm thực địa phương.','COMPLETED',3),
       ('Quảng bá địa điểm du lịch', '2023-05-20 07:20:60 +7:00','2023-05-10 10:00:00 +7:00','2023-05-20 12:00:00 +7:00','Bà rịa vũng tàu','Nhân dịp nghĩ hè ngắn cùng nhau về thăm bà, cụ thể là Bà Rịa Vũng Tàu','1.Thành phố du lịch: Hòa mình vào nhịp sống sôi động và văn hóa đa dạng của những thành phố lớn như Paris, New York, Tokyo hay Barcelona. Tận hưởng kiến trúc độc đáo, nền văn hóa phong phú, mua sắm thả ga và thưởng thức ẩm thực tuyệt vời.\n2.Bãi biển nắng vàng: Tận hưởng những bãi biển tuyệt đẹp với cát trắng mịn, nước biển trong xanh và không khí trong lành. Điều hòa tâm trí và tận hưởng những hoạt động như lướt ván, lặn biển, hay đơn giản là thả mình vào những giây phút thư giãn trên bãi cát.','COMPLETED',3),
       ('Hội An - Khám phá kỳ quan văn hóa', '2023-05-20 07:20:60 +7:00','2023-05-10 10:00:00 +7:00','2023-05-20 12:00:00 +7:00','Hội An','Chúng tôi đang tìm kiếm một KOL đam mê du lịch và ẩm thực, có khả năng quảng bá địa điểm du lịch Hội An, miền Trung Việt Nam. Bạn sẽ có cơ hội trải nghiệm những dịch vụ cao cấp của một khách sạn hàng đầu và tham gia vào các lễ hội độc đáo. Hãy cùng chúng tôi khám phá vẻ đẹp văn hóa và những trải nghiệm tuyệt vời mà Hội An mang lại.','1.Trải nghiệm dịch vụ cao cấp: Bạn sẽ có cơ hội lưu trú tại một khách sạn danh tiếng trong khu vực Hội An, nơi mang đến trải nghiệm lưu trú sang trọng và tiện nghi. Hãy trải qua sự phục vụ chuyên nghiệp, hồ bơi tuyệt đẹp, nhà hàng độc đáo và các tiện ích cao cấp khác.\n2.Tham gia các lễ hội đặc biệt: Hội An nổi tiếng với các lễ hội truyền thống và sự kiện văn hóa. Bạn sẽ có cơ hội tham gia vào những lễ hội như Lễ hội Ánh sáng Lampion, Lễ hội Biển đèn hoặc Lễ hội Trung thu truyền thống. Hãy truyền tải trải nghiệm và cảm nhận sự sôi động và độc đáo của những lễ hội này đến khán giả của bạn.\n3.Khám phá địa điểm du lịch: Hãy tận hưởng một ngày trọn vẹn trong việc khám phá Hội An. Tham quan các di tích lịch sử như Chùa Cầu, Nhà cổ Phùng Hưng và Phố cổ Hội An. Trải nghiệm văn hóa đặc trưng của thành phố cổ bằng cách tham gia vào các hoạt động như học nghề truyền thống, tạo lồng đèn, và thử mua sắm các sản phẩm thủ công độc đáo.\n\nBan đêm, bạn có thể tham gia các hoạt động giải trí như đi dạo trên phố cổ, thưởng thức đồ uống và nhạc sống tại các quán bar và quán cà phê, hoặc tham gia vào những buổi biểu diễn nghệ thuật đường phố tuyệt vời.','COMPLETED',3),
       ('Đắm mình trong trải nghiệm du lịch thư giãn và nghỉ dưỡng tại Bà Nà Hills','2023-01-10 10:00:00 +7:00','2023-02-10 10:00:00 +7:00','2023-03-10 10:00:00 +7:00','Bà Nà Hills - Đà Nẵng','Chúng tôi đang tìm kiếm một KOL đam mê du lịch thư giãn và nghỉ dưỡng để quảng bá cho khu nghỉ dưỡng mới mở Nắng golden. Bạn sẽ có cơ hội trải nghiệm sự sang trọng và thư giãn tuyệt đỉnh, được ở tại những căn phòng tiện nghi và tham gia các dịch vụ cao cấp. Hãy cùng chúng tôi khám phá điểm đến nghỉ dưỡng lý tưởng và chia sẻ trải nghiệm đến với cộng đồng trực tuyến của bạn.','1.Khu nghỉ dưỡng sang trọng: Bạn sẽ được bố trí ở những căn phòng sang trọng và thoải mái với thiết kế hiện đại và tiện nghi đẳng cấp. Tận hưởng không gian riêng tư và cảnh quan tuyệt đẹp của khu nghỉ dưỡng. Hãy chia sẻ trải nghiệm của bạn về không gian nghỉ dưỡng và các tiện ích độc đáo mà nơi này mang lại.\n2.Dịch vụ cao cấp: Khu nghỉ dưỡng [Tên Khu nghỉ dưỡng] mang đến cho bạn những dịch vụ đẳng cấp để tạo ra trải nghiệm tuyệt vời. Hãy tham gia vào các hoạt động như spa, yoga, thể dục và thể thao, hồ bơi, nhà hàng và quầy bar. Chia sẻ với cộng đồng của bạn những trải nghiệm thư giãn và dịch vụ chăm sóc khách hàng xuất sắc mà bạn nhận được','IN_PROGRESS',5),
       ('Du lịch thể thao và phiêu lưu - Trải nghiệm hồi hộp và mạo hiểm trên các cầu kính Trung Quốc','2022-01-01 01:00:00 +7:00','2022-02-01 01:00:00 +7:00','2022-01-02 01:00:00 +7:00','Trung Quốc','Chúng tôi đang tìm kiếm một KOL yêu thích du lịch thể thao và phiêu lưu để chia sẻ trải nghiệm hồi hộp trên các cầu kính ở Trung Quốc. Bạn sẽ có cơ hội khám phá những cầu kính độc đáo và tham gia vào các hoạt động mạo hiểm tại các điểm đến này. Hãy cùng chúng tôi khám phá sự kết hợp giữa thể thao, phiêu lưu và cảm giác hồi hộp trên những cầu kính ấn tượng.','1.Cầu kính độc đáo: Trung Quốc nổi tiếng với những cầu kính độc đáo và táo bạo. Bạn sẽ được tham gia vào việc khám phá các cầu kính như Cầu Zhangjiajie Glass, Cầu Zhangjiajie Grand Canyon và Cầu Tianmen Skywalk. Hãy chia sẻ với cộng đồng của bạn về cảm giác hồi hộp và độc đáo khi đứng trên những cầu kính này.\n2.Trải nghiệm mạo hiểm: Khi tham gia vào các cầu kính, bạn sẽ được trải nghiệm những hoạt động mạo hiểm như đi trên cầu kính, thưởng thức cảnh quan đẹp, hoặc thử những trò chơi mạo hiểm như nhảy bungee từ cầu. Hãy chia sẻ với cộng đồng về cảm giác mạo hiểm và thách thức mà bạn đã trải qua.\n3.Kết hợp thể thao và phiêu lưu: Du lịch thể thao và phiêu lưu trên các cầu kính Trung Quốc mang đến cho bạn trải nghiệm tuyệt vời về sự kết hợp giữa thể thao và mạo hiểm. Hãy chia sẻ về những hoạt động thể thao mà bạn đã tham gia trên cầu kính, chẳng hạn như đi bộ, chạy bộ hoặc leo trèo. Cảm nhận sự kích thích và thử thách mà du lịch thể thao và phiêu lưu này mang lại.','COMPLETED',10),
       ('Du lịch xanh - Trải nghiệm cắm trại hòa mình vào thiên nhiên ở vùng Hòa Bắc - Đà Nẵng','2020-01-10 10:00:00 +7:00','2020-02-10 10:00:00 +7:00','2020-03-10 10:00:00 +7:00','Đà Nẵng','Chúng tôi đang tìm kiếm một KOL yêu thích du lịch xanh và tôn trọng thiên nhiên để chia sẻ trải nghiệm cắm trại hòa mình vào thiên nhiên ở khu vực hồ Bắc Đà Nẵng. Bạn sẽ có cơ hội trải nghiệm cuộc sống gần gũi với thiên nhiên, tận hưởng không gian yên tĩnh và tham gia vào các hoạt động sinh thái bền vững. Hãy cùng chúng tôi khám phá sự hòa mình và tôn trọng thiên nhiên trong cuộc sống cắm trại xanh.','1.Cắm trại giữa thiên nhiên: Bạn sẽ được trải nghiệm cắm trại tại các khu vực xanh tươi và bình yên gần hồ Bắc Đà Nẵng. Thưởng thức không gian tự nhiên, ngắm nhìn cảnh quan đẹp và tận hưởng sự yên tĩnh của thiên nhiên xung quanh. Hãy chia sẻ trải nghiệm của bạn về việc sống gần gũi với thiên nhiên và cảm nhận sự bình yên mà nó mang lại.\n2.Hoạt động sinh thái bền vững: Trong cuộc sống cắm trại xanh, bạn sẽ có cơ hội tham gia vào các hoạt động sinh thái bền vững như đi bộ đường mòn tự nhiên, thả mình vào hồ để tắm và tham gia vào việc bảo vệ môi trường như thu gom rác thải. Hãy chia sẻ với cộng đồng của bạn về việc tham gia vào các hoạt động bảo vệ môi trường và xây dựng một cộng đồng du lịch xanh.\n3.Khám phá văn hóa địa phương: Bạn sẽ có cơ hội tìm hiểu về văn hóa địa phương và giao lưu với cộng đồng trong khu vực hồ Bắc Đà Nẵng. Tham gia vào các hoạt động như học nghề truyền thống, thăm các làng nghề địa phương và thưởng thức ẩm thực địa phương. ','IN_PROGRESS',5),
       ('Kem chống nắng - Trải nghiệm miễn phí 6 tháng cho làn da đẹp','2023-04-20 10:00:00 +7:00','2023-04-25 10:00:00 +7:00','2023-07-25 10:00:00 +7:00','137 - Nguyễn Văn Linh - Đà Nẵng','Chúng tôi đang tìm kiếm một KOL có làn da đẹp và quan tâm đến việc bảo vệ da khỏi tác động của ánh nắng mặt trời để quảng bá cho kem chống nắng. Bạn sẽ có cơ hội trải nghiệm miễn phí kem chống nắng trong 6 tháng và nhận các ưu đãi đặc biệt khác. Hãy cùng chúng tôi chia sẻ về lợi ích và sức mạnh của kem chống nắng trong việc bảo vệ làn da khỏi tác động của tia UV và khám phá sự tự tin mà nó mang lại.','1.Trải nghiệm miễn phí 6 tháng: Bạn sẽ nhận được kem chống nắng miễn phí trong 6 tháng để thử nghiệm và chia sẻ trải nghiệm của mình. Được cung cấp một dòng sản phẩm chất lượng cao, chúng tôi mong muốn bạn trải nghiệm sự hiệu quả và an toàn của kem chống nắng trong việc bảo vệ da khỏi tác động của ánh nắng mặt trời.\n2.Làn da đẹp: Chúng tôi tìm kiếm KOL có làn da đẹp và khỏe mạnh để chia sẻ câu chuyện về việc sử dụng kem chống nắng và tác động tích cực của nó đối với làn da. Hãy chia sẻ về việc duy trì và cải thiện làn da đẹp của bạn thông qua việc sử dụng kem chống nắng và các biện pháp bảo vệ da khác.\n3.Ưu đãi đặc biệt: Ngoài việc được sử dụng kem chống nắng miễn phí, bạn còn sẽ được nhận các ưu đãi đặc biệt khác. Đây có thể là các phiếu giảm giá cho các sản phẩm chăm sóc da khác, quà tặng đi kèm hoặc tham gia vào chương trình đặc biệt. Hãy chia sẻ với cộng đồng về những ưu đãi đặc biệt mà bạn nhận được và sự hài lòng với sản phẩm kem chống nắng.','IN_PROGRESS',14);


insert into campaign_images(campaign_id, image_id)
values (1,	48),
       (1,	49),
       (1,	50),
       (1,	51),
       (1,	52),
       (2,	53),
       (2,	54),
       (2,	55),
       (2,	56),
       (3,	57),
       (3,	58),
       (3,	59),
       (3,	60),
       (4,	61),
       (4,	62),
       (4,	63),
       (4,	64),
       (5,	65),
       (5,	66),
       (5,	67),
       (5,	68),
       (6,	69),
       (6,	70),
       (6,	71),
       (6,	72),
       (7,	73),
       (7,	74),
       (7,	75),
       (7,	76),
       (7,	77),
       (7,	78),
       (8,	79),
       (8,	80),
       (8,	81),
       (8,	82);


insert into campaign_fields(campaign_id, field_id)
values (1, 5),
       (1, 12),
       (1, 14),
       (2, 2),
       (2, 3),
       (3, 3),
       (4, 3),
       (5, 3),
       (5, 5),
       (5, 9),
       (6, 3),
       (7, 3),
       (8, 1),
       (8, 7);