insert into enterprises(user_id, name, phone, tax_id, city_id, introduction)
values (51, 'Công TY TNHH MTV Sang Đỗ', '0123456789', '3216549873216', 30, 'Sang Enterprise là một doanh nghiệp công nghệ đa ngành hoạt động tại Việt Nam. Với hơn 10 năm kinh nghiệm, công ty đã xây dựng một tên tuổi mạnh mẽ và trở thành một trong những doanh nghiệp hàng đầu trong lĩnh vực công nghệ . Sang Enterprise cung cấp một loạt các dịch vụ và sản phẩm công nghệ đa dạng, bao gồm phát triển phần mềm, thiết kế web và ứng dụng di động, quản lý hệ thống và mạng, giải pháp IoT (Internet of Things), trí tuệ nhân tạo (AI), và nhiều lĩnh vực công nghệ khác. Với đội ngũ chuyên gia tài năng và giàu kinh nghiệm, Sang Enterprise đã thành công trong việc triển khai các dự án công nghệ lớn và phức tạp cho khách hàng từ các ngành công nghiệp khác nhau, bao gồm tài chính, y tế, giáo dục, và thương mại điện tử. Sự cam kết với chất lượng, sự sáng tạo và khả năng thích nghi nhanh chóng với các xu hướng công nghệ mới đã giúp Sang Enterprise xây dựng mối quan hệ đáng tin cậy với khách hàng và đạt được nhiều thành công đáng chú ý trong ngành công nghệ tại Việt Nam.'),
       (52, 'Công TY TNHH MTV thành viên Huy Trần', '0123456789', '1234567891234', 31, 'Huy Enterprise là một doanh nghiệp đa ngành tại Việt Nam, hoạt động chủ yếu trong lĩnh vực bất động sản. Với hơn 25 năm kinh nghiệm, Sunshine Corporation đã xây dựng một tên tuổi mạnh mẽ và trở thành một trong những công ty hàng đầu trong ngành này. Huy Enterprise tập trung vào phát triển và đầu tư vào các dự án bất động sản đa dạng, bao gồm căn hộ chung cư, khu đô thị, biệt thự, và khu nghỉ dưỡng. Các dự án của Huy Enterprise được thiết kế với tiêu chuẩn cao, sử dụng công nghệ tiên tiến và mang đến không gian sống đẳng cấp cho khách hàng. Ngoài lĩnh vực bất động sản, Huy Enterprise cũng hoạt động trong các lĩnh vực liên quan như xây dựng, năng lượng tái tạo và khách sạn. Công ty đã thành công trong việc triển khai nhiều dự án lớn và mang lại giá trị đáng kể cho khách hàng và cộng đồng. Sự cam kết với chất lượng, sự sáng tạo và tầm nhìn bền vững đã giúp Huy Enterprise trở thành một trong những doanh nghiệp hàng đầu trong ngành bất động sản tại Việt Nam. Công ty không chỉ xây dựng các công trình chất lượng mà còn tạo ra môi trường sống và làm việc tốt cho cộng đồng và môi trường xung quanh.'),
       (53, 'Công TY TNHH MTV thành viên Thắng Trần', '0123456789', '9876543219876', 32, 'Thang Enterprise là một doanh nghiệp sản xuất hàng tiêu dùng hàng đầu tại Việt Nam. Với hơn 20 năm kinh nghiệm, công ty đã xây dựng một vị thế mạnh mẽ và trở thành một trong những doanh nghiệp hàng đầu trong ngành sản xuất. Thang Enterprise chuyên sản xuất và cung cấp một loạt các sản phẩm hàng tiêu dùng phổ biến, bao gồm đồ điện gia dụng, sản phẩm nhựa, sản phẩm chăm sóc cá nhân và nhiều loại hàng hóa khác. Công ty đảm bảo chất lượng cao, tuân thủ các quy định an toàn và môi trường, và luôn đáp ứng nhu cầu đa dạng của khách hàng. Thang Enterprise có cơ sở sản xuất hiện đại, sử dụng công nghệ tiên tiến và quy trình sản xuất hiệu quả. Đội ngũ kỹ thuật viên và nhân viên tận tâm và có kinh nghiệm đảm bảo rằng mọi sản phẩm được sản xuất với chất lượng cao và đáp ứng đúng tiêu chuẩn. Với tầm nhìn về sự phát triển và cam kết với chất lượng, Thang Enterprise đã xây dựng được lòng tin của khách hàng trong nước và quốc tế. Công ty không chỉ đáp ứng nhu cầu hàng tiêu dùng mà còn đóng góp vào sự phát triển kinh tế và xã hội của đất nước.'),
       (54, 'Công TY TNHH MTV thành viên Chân Phạm', '0123456789', '7894561237894', 33, 'Chan Enterprise là một doanh nghiệp công nghệ đổi mới tại Việt Nam. Với sự chuyên môn và sáng tạo, công ty đã xây dựng một tên tuổi đáng chú ý và trở thành một trong những doanh nghiệp hàng đầu trong ngành công nghệ. Chan Enterprise chuyên phát triển và cung cấp các giải pháp công nghệ thông tin và phần mềm cho các công ty và tổ chức. Các dịch vụ bao gồm phát triển ứng dụng di động, phần mềm tùy chỉnh, giải pháp điện toán đám mây, phân tích dữ liệu và trí tuệ nhân tạo. Công ty tập trung vào việc tạo ra các sản phẩm và dịch vụ thông minh, tiện ích và mang lại giá trị gia tăng cho khách hàng. Chan Enterprise có đội ngũ kỹ sư và chuyên gia có kinh nghiệm và tài năng trong việc áp dụng công nghệ hiện đại và quy trình phát triển chuyên nghiệp. Công ty luôn đặt sự sáng tạo và chất lượng lên hàng đầu, đáp ứng đúng yêu cầu và kỳ vọng của khách hàng. Với tầm nhìn về sự đổi mới và cam kết với chất lượng, Chan Enterprise đã xây dựng mối quan hệ đáng tin cậy với khách hàng và đạt được thành công trong việc triển khai các dự án công nghệ quan trọng. Công ty không chỉ mang lại lợi ích kinh tế mà còn góp phần vào sự phát triển bền vững của ngành công nghệ tại Việt Nam.'),
       (55, 'Công ty TNHH 1 thành viên Hiếu Văn', '0123456789', '6549873216549', 34, 'Hieu Enterprise là một doanh nghiệp thực phẩm đa quốc gia hoạt động tại Việt Nam. Với sự đa dạng và chất lượng sản phẩm, công ty đã xây dựng một thương hiệu danh tiếng và trở thành một trong những doanh nghiệp hàng đầu trong ngành thực phẩm. Hieu Enterprise chuyên nhập khẩu và phân phối các loại thực phẩm và đồ uống từ các quốc gia khác nhau trên toàn thế giới. Các sản phẩm bao gồm hải sản, thịt, rau củ quả, sản phẩm đồ ngọt, đồ uống và nhiều loại thực phẩm khác. Công ty cam kết cung cấp những sản phẩm chất lượng, an toàn và đáp ứng nhu cầu đa dạng của khách hàng.Hieu Enterprise có mạng lưới phân phối rộng khắp và đối tác chiến lược với các nhà sản xuất uy tín trên thế giới. Công ty tuân thủ các quy định về an toàn thực phẩm và quy trình kiểm soát chất lượng nghiêm ngặt để đảm bảo sản phẩm đạt tiêu chuẩn cao nhất. Với tầm nhìn quốc tế và cam kết với chất lượng, Hieu Enterprise đã xây dựng được lòng tin của khách hàng và mở rộng thị trường cả trong nước và quốc tế. Công ty không chỉ mang lại những sản phẩm thực phẩm chất lượng mà còn góp phần vào việc đem đến trải nghiệm ẩm thực đa dạng và phong phú cho người tiêu dùng tại Việt Nam.'),
       (56, 'CÔNG TY TNHH DỊCH VỤ DU LỊCH BIỂN ĐÀ NẴNG', '0259418932', '0402173394', 35, 'DaNang Beach là một doanh nghiệp hoạt động trong lĩnh vực du lịch tại Đà Nẵng. Với sự chuyên nghiệp và tận tâm, công ty đã xây dựng một danh tiếng và trở thành một trong những đơn vị hàng đầu trong ngành du lịch.DaNang Beach tập trung vào việc cung cấp các dịch vụ lưu trú và trải nghiệm du lịch chất lượng cao. Công ty sở hữu và quản lý các khu nghỉ dưỡng và khách sạn tại các địa điểm nổi tiếng trên khắp Việt Nam, từ bãi biển tuyệt đẹp đến các khu vực núi rừng hoang sơ. DaNang Beach cam kết đem đến cho khách hàng những trải nghiệm du lịch đáng nhớ. Các khu nghỉ dưỡng và khách sạn được thiết kế với kiến trúc độc đáo, tiện nghi hiện đại và dịch vụ chuyên nghiệp. Công ty cung cấp các hoạt động giải trí, thể thao và thư giãn để khách hàng có thể tận hưởng những khoảnh khắc thú vị và thư giãn tuyệt đối. Với tầm nhìn về sự phát triển bền vững và cam kết với chất lượng dịch vụ, DaNang Beach đã xây dựng được lòng tin của khách hàng và đạt được thành công trong việc thu hút du khách từ cả trong và ngoài nước. Công ty không chỉ đóng góp vào sự phát triển kinh tế của địa phương mà còn giúp quảng bá hình ảnh Việt Nam là một điểm đến du lịch hấp dẫn và đáng để khám phá.'),
       (57, 'VĂN PHÒNG LUẬT SƯ NGUYỄN TRÚC', '0766712335', '0402173027', 36, 'Văn Phòng luật sư Nguyễn Trúc là một doanh nghiệp hoạt động trong lĩnh vực luật sư tại Việt Nam. Với đội ngũ luật sư tài năng và kinh nghiệm, công ty đã xây dựng một danh tiếng vững chắc và trở thành một trong những đơn vị hàng đầu trong ngành luật. Nguyễn Trúc cung cấp các dịch vụ pháp lý đa dạng cho khách hàng, bao gồm tư vấn pháp lý, giải quyết tranh chấp, lập hợp đồng và thủ tục pháp lý khác. Công ty chuyên về nhiều lĩnh vực luật, bao gồm luật doanh nghiệp, luật lao động, luật dân sự, luật hợp đồng, và nhiều lĩnh vực khác. Nguyễn Trúc nắm vững kiến thức pháp lý và hiểu rõ quy định pháp luật tại Việt Nam. Đội ngũ luật sư có chuyên môn cao và kỹ năng tư duy pháp lý sắc bén, đảm bảo khách hàng nhận được sự tư vấn và đại diện pháp lý chất lượng cao. Với tầm nhìn về sự công bằng và cam kết với chất lượng dịch vụ, Nguyễn Trúc đã xây dựng lòng tin của khách hàng và đạt được thành công trong việc giải quyết các vụ việc pháp lý phức tạp. Công ty không chỉ hỗ trợ khách hàng trong việc bảo vệ quyền lợi và lợi ích của họ mà còn đóng góp vào sự phát triển của hệ thống pháp luật tại Việt Nam.'),
       (58, 'CÔNG TY TNHH TN TRAVEL', '0744205170', '0402172841', 37, 'TN Travel là công ty lữ hành hàng đầu hoạt động trong lĩnh vực du lịch tại Việt Nam. Với sự tập trung mạnh mẽ vào sự hài lòng của khách hàng và trải nghiệm du lịch đáng nhớ, công ty đã tạo dựng được uy tín và trở thành sự lựa chọn đáng tin cậy của du khách. TN Travel cung cấp nhiều loại hình dịch vụ phục vụ nhu cầu du lịch đa dạng. Họ chuyên tổ chức và điều phối các tour du lịch trong nước và quốc tế, bao gồm các tour du lịch văn hóa, du lịch mạo hiểm, du lịch sinh thái và du lịch trải nghiệm cao cấp. Công ty đảm bảo hành trình được cá nhân hóa, chỗ ở thoải mái, phương tiện di chuyển đáng tin cậy và hướng dẫn viên du lịch am hiểu để mang đến cho khách hàng những trải nghiệm du lịch đặc biệt. Với đội ngũ chuyên gia du lịch và chuyên gia điểm đến giàu kinh nghiệm, TN Travel sở hữu kiến thức chuyên sâu về các điểm đến du lịch khác nhau trên toàn thế giới và mạng lưới các đối tác đáng tin cậy trên toàn thế giới. Họ cố gắng tạo ra các gói du lịch độc đáo và được thiết kế riêng để giới thiệu vẻ đẹp, văn hóa và các điểm tham quan của Việt Nam và hơn thế nữa. TN Travel cam kết thực hành du lịch có trách nhiệm, thúc đẩy du lịch bền vững, tôn trọng môi trường và cộng đồng địa phương. TN Travel tích cực hỗ trợ các sáng kiến địa phương và hợp tác với các doanh nghiệp địa phương để mang đến những trải nghiệm đích thực đồng thời đóng góp vào sự phát triển kinh tế xã hội của các điểm đến mà họ hoạt động. một cơ sở khách hàng rộng lớn. Niềm đam mê du lịch và sự chú ý đến từng chi tiết của họ đã tạo nên mỗi hành trình là những kỷ niệm khó quên, đáng trân trọng cho du khách khám phá những điều kỳ diệu của Việt Nam và hơn thế nữa.'),
       (59, 'CÔNG TY TNHH MTV THÀNH HƯNG EXPRESS', '0949793909', '0402172506', 38, 'Thành Hưng Logistics là một doanh nghiệp vận chuyển hàng hóa hàng đầu tại Việt Nam. Với một hệ thống vận chuyển toàn diện và chuyên nghiệp, công ty đã xây dựng một danh tiếng vững chắc trong ngành vận tải. Thành Hưng Logistics cung cấp các dịch vụ vận chuyển hàng hóa đa dạng, bao gồm vận chuyển đường bộ, đường hàng không, và đường biển. Công ty có một đội ngũ lái xe, nhân viên giao hàng và chuyên viên vận chuyển có kinh nghiệm và được đào tạo chuyên sâu để đảm bảo hàng hóa được vận chuyển an toàn và đúng thời gian. Thành Hưng Logistics đặt chất lượng dịch vụ và sự hài lòng của khách hàng lên hàng đầu. Công ty sử dụng công nghệ tiên tiến và quy trình vận hành hiệu quả để đảm bảo quy trình vận chuyển được thực hiện một cách chính xác và nhanh chóng. Họ cung cấp theo dõi hàng hóa và thông tin vận chuyển liên tục để khách hàng có thể theo dõi quá trình vận chuyển của mình. Với tầm nhìn về sự phát triển và cam kết với chất lượng dịch vụ, Thành Hưng Logistics đã xây dựng lòng tin của khách hàng và đạt được thành công trong việc phục vụ các khách hàng trong nhiều ngành công nghiệp khác nhau. Công ty không chỉ giúp khách hàng vận chuyển hàng hóa một cách an toàn và đáng tin cậy mà còn đóng góp vào sự phát triển của ngành vận tải và kinh tế nước.'),
       (60, 'CÔNG TY TNHH TƯ VẤN THIẾT KẾ & XÂY DỰNG QUANG TRUNG', '0541725449', '0402172753', 39, 'Quang Trung Logistics là một doanh nghiệp vận chuyển hàng hóa hàng đầu tại Việt Nam. Với một hệ thống vận chuyển toàn diện và chuyên nghiệp, công ty đã xây dựng một danh tiếng vững chắc trong ngành vận tải. Quang Trung Logistics cung cấp các dịch vụ vận chuyển hàng hóa đa dạng, bao gồm vận chuyển đường bộ, đường hàng không, và đường biển. Công ty có một đội ngũ lái xe, nhân viên giao hàng và chuyên viên vận chuyển có kinh nghiệm và được đào tạo chuyên sâu để đảm bảo hàng hóa được vận chuyển an toàn và đúng thời gian. Quang Trung Logistics đặt chất lượng dịch vụ và sự hài lòng của khách hàng lên hàng đầu. Công ty sử dụng công nghệ tiên tiến và quy trình vận hành hiệu quả để đảm bảo quy trình vận chuyển được thực hiện một cách chính xác và nhanh chóng. Họ cung cấp theo dõi hàng hóa và thông tin vận chuyển liên tục để khách hàng có thể theo dõi quá trình vận chuyển của mình. Với tầm nhìn về sự phát triển và cam kết với chất lượng dịch vụ, Quang Trung Logistics đã xây dựng lòng tin của khách hàng và đạt được thành công trong việc phục vụ các khách hàng trong nhiều ngành công nghiệp khác nhau. Công ty không chỉ giúp khách hàng vận chuyển hàng hóa một cách an toàn và đáng tin cậy mà còn đóng góp vào sự phát triển của ngành vận tải và kinh tế nước.'),
       (61, 'CÔNG TY TNHH TƯ VẤN GIÁO DỤC QUỐC TẾ KHÁT VỌNG XANH', '0928680910', '0402172672', 40, 'Khát Vọng Xanh là một doanh nghiệp hàng đầu trong lĩnh vực nông nghiệp tại Việt Nam. Với sự chuyên nghiệp và cam kết với nông nghiệp bền vững, công ty đã xây dựng được danh tiếng vững chắc và trở thành một đối tác đáng tin cậy trong ngành. Khát Vọng Xanh tập trung vào sản xuất và kinh doanh các sản phẩm nông nghiệp chất lượng cao như cây trồng, thực phẩm hữu cơ, và các sản phẩm chế biến từ nông sản. Công ty áp dụng các phương pháp canh tác hiện đại, sử dụng công nghệ tiên tiến và tuân thủ các tiêu chuẩn chất lượng nghiêm ngặt để đảm bảo sự an toàn và chất lượng của sản phẩm. Khát Vọng Xanh đặt mục tiêu phát triển nông nghiệp bền vững, tôn trọng môi trường và giữ gìn sự cân bằng sinh thái. Công ty sử dụng các phương pháp canh tác hữu cơ, tối ưu hóa sử dụng tài nguyên và giảm thiểu tác động tiêu cực lên môi trường. Đồng thời, công ty cũng đóng góp vào cộng đồng bằng việc tạo ra việc làm và hỗ trợ các nông dân địa phương. Với đội ngũ chuyên gia và nhân viên giàu kinh nghiệm trong lĩnh vực nông nghiệp, Khát Vọng Xanh đảm bảo rằng mỗi khách hàng nhận được sự tư vấn và hỗ trợ tận tâm. Công ty không chỉ tập trung vào sự phát triển kinh doanh mà còn đặt lợi ích của khách hàng và cộng đồng lên hàng đầu. Khát Vọng Xanh đóng góp vào năng suất nông nghiệp và an ninh lương thực của Việt Nam, đồng thời góp phần vào sự phát triển bền vững của ngành nông nghiệp và môi trường tự nhiên.'),
       (62, 'Công Ty Thiết Kế và Xây Dựng M-House', '0207380050', '0402071307', 41, 'M-House là một doanh nghiệp hàng đầu trong lĩnh vực nội thất tại Việt Nam. Với sự chú trọng đến thiết kế sáng tạo và chất lượng sản phẩm, công ty đã xây dựng một danh tiếng vững chắc và trở thành điểm đến lý tưởng cho khách hàng tìm kiếm sự sang trọng và đẳng cấp trong không gian sống của mình. M-House cung cấp một bộ sưu tập đa dạng của nội thất cao cấp và độc đáo, bao gồm các sản phẩm như sofa, bàn ăn, giường ngủ, tủ kệ, và các vật trang trí nội thất khác. Công ty kết hợp giữa kiến ​​thức chuyên môn và ý tưởng sáng tạo để tạo ra các sản phẩm thiết kế độc đáo và phong cách, mang đến cho khách hàng không gian sống tinh tế và đẳng cấp. M-House đặt chất lượng sản phẩm lên hàng đầu. Công ty sử dụng các nguyên liệu cao cấp và áp dụng quy trình sản xuất chất lượng cao để đảm bảo sự bền bỉ và đẹp mắt của sản phẩm. Bên cạnh đó, công ty cũng đề cao sự thoải mái và tiện nghi trong thiết kế, đảm bảo rằng mỗi sản phẩm đều đáp ứng được nhu cầu và sở thích của khách hàng. Với đội ngũ thiết kế giàu kinh nghiệm và tận tâm, M-House cam kết đáp ứng tốt nhất mọi yêu cầu của khách hàng. Công ty tư vấn và hỗ trợ khách hàng trong quá trình lựa chọn sản phẩm, thiết kế không gian và tạo ra không gian sống tinh tế và phong cách. M-House góp phần tạo nên không gian sống đẳng cấp và sang trọng cho khách hàng. Bằng cách kết hợp giữa sự sáng tạo, chất lượng và dịch vụ tận tâm, công ty đã xây dựng được lòng tin và sự hài lòng của khách hàng trong ngành nội thất tại Việt Nam.'),
       (63, 'Công Ty CP Acecook', '0769537629', '0300808687', 42, 'Acecook là một doanh nghiệp hàng đầu trong lĩnh vực thực phẩm tại Việt Nam. Với cam kết đem đến những sản phẩm thực phẩm chất lượng cao và an toàn, công ty đã xây dựng được danh tiếng vững chắc và trở thành lựa chọn tin cậy của người tiêu dùng. Acecook chuyên sản xuất và cung cấp các sản phẩm thực phẩm đa dạng như thịt, hải sản, đồ uống, đồ ăn nhanh và các loại thực phẩm chế biến sẵn. Công ty sử dụng nguyên liệu tươi ngon và tuân thủ các tiêu chuẩn vệ sinh và an toàn thực phẩm nghiêm ngặt trong quá trình sản xuất. Đội ngũ kỹ thuật viên và chuyên gia dinh dưỡng của công ty đảm bảo rằng mỗi sản phẩm đáp ứng được yêu cầu dinh dưỡng và hương vị tốt nhất. Acecook đặt sự an toàn và chất lượng của sản phẩm lên hàng đầu. Công ty thường xuyên kiểm tra và giám sát quá trình sản xuất để đảm bảo tuân thủ các quy định về an toàn thực phẩm. Bên cạnh đó, công ty cũng tập trung vào việc nâng cao trải nghiệm khách hàng bằng cách cung cấp dịch vụ chuyên nghiệp và tư vấn dinh dưỡng. Với tầm nhìn về sự phát triển và cam kết với chất lượng, Acecookđã xây dựng được lòng tin của khách hàng và đạt được thành công trong việc mở rộng thị trường và tạo dựng mối quan hệ đối tác lâu dài. Công ty không chỉ đóng góp vào sự phát triển kinh tế mà còn đảm bảo sự phục vụ tốt nhất cho nhu cầu dinh dưỡng và sức khỏe của người tiêu dùng.'),
       (64, 'Công Ty TNHH Matrix', '02366295295', '0400426522', 43, 'Công Ty TNHH Matrix Việt Nam là một doanh nghiệp hoạt động trong lĩnh vực công nghệ thông tin và phần mềm. Với sứ mệnh đem đến các giải pháp công nghệ đột phá và chất lượng, công ty đã xây dựng được vị thế và danh tiếng vững chắc trong ngành. Matrix Việt Nam tập trung vào phát triển và triển khai các phần mềm ứng dụng, các giải pháp phần mềm doanh nghiệp và dịch vụ tư vấn công nghệ thông tin. Công ty sở hữu đội ngũ kỹ sư và chuyên gia có kinh nghiệm và kiến thức sâu rộng về công nghệ, giúp đưa ra những sản phẩm và dịch vụ đáp ứng tốt nhất yêu cầu của khách hàng. Matrix Việt Nam đặt chất lượng và sự đổi mới lên hàng đầu. Công ty áp dụng các tiêu chuẩn quản lý chất lượng cao như ISO 9001 để đảm bảo quá trình phát triển và triển khai sản phẩm đạt được hiệu quả và chất lượng cao. Ngoài ra, công ty liên tục nghiên cứu và đầu tư vào nghiên cứu và phát triển công nghệ mới nhằm cung cấp các giải pháp tiên tiến và đáng tin cậy cho khách hàng. Với phương châm phục vụ tận tâm và đồng hành cùng khách hàng, Matrix Việt Nam cam kết mang đến giải pháp công nghệ thông tin toàn diện và hỗ trợ khách hàng trong việc nâng cao hiệu suất và cạnh tranh của doanh nghiệp. Công ty không chỉ tập trung vào việc phát triển kinh doanh mà còn xây dựng mối quan hệ đối tác bền vững và tạo sự hài lòng cho khách hàng. Matrix Việt Nam góp phần vào sự phát triển của ngành công nghệ thông tin tại Việt Nam và đóng góp vào sự nâng cao năng lực cạnh tranh của các doanh nghiệp. Bằng việc kết hợp giữa sự chuyên nghiệp, chất lượng và sự đổi mới, công ty đã xây dựng được lòng tin của khách hàng và trở thành một đối tác đáng tin cậy trong lĩnh vực công nghệ thông tin.'),
       (65, 'Công Ty mỹ phẩm Naunau', '0854205170', '0422426533', 44, 'Naunau Beauty là một doanh nghiệp hàng đầu trong lĩnh vực mỹ phẩm tại Việt Nam. Với sứ mệnh mang đến sự tự tin và sắc đẹp cho mọi người, công ty đã xây dựng được tên tuổi và niềm tin từ khách hàng. Naunau Beauty chuyên sản xuất và cung cấp các sản phẩm mỹ phẩm đa dạng như kem dưỡng da, mặt nạ, son môi, phấn mắt và các sản phẩm chăm sóc cá nhân. Công ty sử dụng các thành phần tự nhiên và công nghệ tiên tiến để đảm bảo chất lượng cao và an toàn cho người sử dụng. Đội ngũ chuyên gia và nhà nghiên cứu của công ty luôn theo dõi xu hướng và công nghệ mới nhất để mang đến những sản phẩm tiên tiến và hiệu quả. Naunau Beauty cam kết đặt chất lượng và sự tận hưởng của khách hàng lên hàng đầu. Công ty thường xuyên tiến hành kiểm tra chất lượng nghiêm ngặt và tuân thủ các tiêu chuẩn an toàn trong quá trình sản xuất. Đồng thời, công ty không ngừng nghiên cứu và phát triển để đáp ứng nhu cầu và mong muốn của khách hàng về mỹ phẩm. Naunau Beauty không chỉ mang đến những sản phẩm chất lượng mà còn tạo ra trải nghiệm mua sắm tuyệt vời cho khách hàng. Công ty tạo ra các dịch vụ chăm sóc khách hàng tận tâm và tư vấn chuyên nghiệp để giúp khách hàng lựa chọn sản phẩm phù hợp và tận hưởng tối đa lợi ích từ mỹ phẩm. Với tầm nhìn về vẻ đẹp tự nhiên và sự phục vụ tận tâm, Naunau Beauty đã xây dựng được lòng tin và sự hài lòng từ khách hàng. Công ty không chỉ đóng góp vào sự phát triển của ngành mỹ phẩm mà còn giúp nâng cao tự tin và sắc đẹp cho hàng triệu người tiêu dùng tại Việt Nam.'),
       (66, 'Công Ty cổ phần Sao Thái Dương', '18001799', '0101252356', 45, null),
       (67, 'Mỹ phẩm Việt Hương', '0961957087', '0314537860', 46, null),
       (68, 'Công TY TNHH mỹ phẩm Hani', '0964777017 (', '0422537860', 47, null),
       (69, 'Yody', '18002086', '0801206940', 48, null),
       (70, 'Nowsaigon', '0933782768', '0433417860', 49, null),
       (71, 'CÔNG TY TNHH THỜI TRANG ELISE', '19003060', '0108393204', 50, null),
       (72, 'CÔNG TY TNHH THỜI TRANG IVY MODA', '0905898683', '0105777650', 30, null),
       (73, 'CÔNG TY TNHH THỜI TRANG AN PHƯỚC', '02838350059', '0301241545', 31, null),
       (74, 'Công Ty TNHH Phạm Bình Education', '02746501164', '0211241545', 32, null),
       (75, 'Công Ty Cổ Phần Giáo Dục Hoàng Gia', '039105680', '0212537860', 33, null),
       (76, 'Trung Tâm Ngoại Ngữ Gic', '0916151937', '0301141545', 34, null),
       (77, 'CÔNG TY TNHH HEALTHY HERBS HAPPY LIFE TIFFANY', '0934899585', '0402192100', 35, null),
       (78, 'CÔNG TY TNHH THIẾT KẾ VÀ XÂY DỰNG AH GLOBAL', '0708117505', '0402191315', 36, null),
       (79, 'CÔNG TY TNHH XUÂN HUY DÉCOR', '0615201577', '0402189820', 37, null),
       (80, 'CÔNG TY TNHH THƯƠNG MẠI TỔNG HỢP TRUNG GIANG', '0915010268', '0402189997', 38, null),
       (81, 'CÔNG TY TNHH DƯỢC PHẨM THIÊN THỊNH PHÚ', '0905446556', '0402189348', 39, null),
       (82, 'CÔNG TY TNHH BẤT ĐỘNG SẢN PHỤNG HOÀNG', '0914682252', '0402188873', 40, null),
       (83, 'CÔNG TY TNHH DANHSON GROUP', '0889816665', '0402188471', 41, null),
       (84, 'Công Ty TNHH Phát Triển Công Nghệ NEWSTAR', '0905111340', '0401835581', 42, null),
       (85, 'Công Ty Cổ Phần Công Nghệ Thành Việt', '0943184343', '0401473116', 43, null),
       (86, 'CÔNG TY CỔ PHẦN DU LỊCH DANAGO', '0833888404', '0491473116', 44, null),
       (87, 'CÔNG TY DU LỊCH GREEN TOUR', '0914800544', '041913374', 45, null),
       (88, 'SAIGONTOURIST - CN ĐÀ NẴNG', '038279279 ', '0310891532 ', 46, null),
       (89, 'CÔNG TY TNHH K - THẨM MỸ VIỆN HÀN QUỐC', '0943214343', '0402191925', 47, null),
       (90, 'CÔNG TY TNHH THIẾT KẾ THI CÔNG NỘI THẤT THÁI HƯNG THỊNH', '0358362429', '0402191185', 48, null),
       (91, 'CÔNG TY TNHH MINH SAN TRAVEL', '0956754619', '0402191731', 49, null),
       (92, 'CÔNG TY TNHH GIÁO DỤC TRÍ THỨC VIỆT', '0843307029', '0402191812', 50, null),
       (93, 'CÔNG TY TNHH SENDY SPA', '0315873683', '0402191650', 51, null),
       (94, 'DOANH NGHIỆP TN KHÁCH SẠN NHÀ NGHỈ TRƯỜNG GIA', '0443614370', '0402191026', 52, null),
       (95, 'CÔNG TY TNHH CÔNG NGHỆ TAGGO', '0970387388', '0402189796', 53, null);

insert into enterprise_fields (enterprise_id, field_id)
values (1, 19),
       (1, 20),
       (1, 21),
       (2, 22),
       (2, 23),
       (2, 24),
       (3, 25),
       (3, 26),
       (3, 27),
       (4, 28),
       (4, 29),
       (4, 19),
       (5, 20),
       (5, 21),
       (5, 22),
       (6, 23),
       (6, 24),
       (6, 25),
       (7, 26),
       (7, 27),
       (7, 28),
       (8, 29),
       (8, 19),
       (8, 20),
       (9, 21),
       (9, 22),
       (9, 23),
       (10, 24),
       (10, 25),
       (10, 26),
       (11, 27),
       (11, 28),
       (11, 29),
       (12, 19),
       (12, 20),
       (12, 21),
       (13, 22),
       (13, 23),
       (13, 24),
       (14, 25),
       (14, 26),
       (14, 27),
       (15, 28),
       (15, 29),
       (15, 19),
       (16, 20),
       (16, 21),
       (16, 22),
       (17, 23),
       (17, 24),
       (17, 25),
       (18, 26),
       (18, 27),
       (18, 28),
       (19, 29),
       (19, 19),
       (19, 20),
       (20, 21),
       (20, 22),
       (20, 23),
       (21, 24),
       (21, 25),
       (21, 26),
       (22, 27),
       (22, 28),
       (22, 29),
       (23, 19),
       (23, 20),
       (23, 21),
       (24, 22),
       (24, 23),
       (24, 24),
       (25, 25),
       (25, 26),
       (25, 27),
       (26, 28),
       (26, 29),
       (26, 19),
       (27, 20),
       (27, 21),
       (27, 22),
       (28, 23),
       (28, 24),
       (28, 25),
       (29, 26),
       (29, 27),
       (29, 28),
       (30, 29),
       (30, 19),
       (30, 20),
       (31, 21),
       (31, 22),
       (31, 23),
       (32, 24),
       (32, 25),
       (32, 26),
       (33, 27),
       (33, 28),
       (33, 29),
       (34, 19),
       (34, 20),
       (34, 21),
       (35, 22),
       (35, 23),
       (35, 24),
       (36, 25),
       (36, 26),
       (36, 27),
       (37, 28),
       (37, 29),
       (37, 19),
       (38, 20),
       (38, 21),
       (38, 22),
       (39, 23),
       (39, 24),
       (40, 25),
       (40, 26),
       (40, 27),
       (41, 28),
       (41, 29),
       (41, 19),
       (42, 20),
       (42, 21),
       (42, 22),
       (43, 23),
       (43, 24),
       (43, 25),
       (44, 26),
       (44, 27),
       (44, 28),
       (45, 29),
       (45, 19),
       (45, 20);