insert into users(first_name, last_name, email, password, avatar, role)
values ('admin', 'admin', 'admin@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'ADMIN');

insert into users(first_name, last_name, email, password, avatar, role)
values ('Sang', 'KOL', 'sangkol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Sang_avatar.png', 'KOL'),
       ('Huy', 'KOL', 'huykol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Huy_avatar.png', 'KOL'),
       ('Thắng', 'KOL', 'thangkol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Thang_avatar.png', 'KOL'),
       ('Chân', 'KOL', 'chankol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Chan_avatar.png', 'KOL'),
       ('Hiếu', 'KOL', 'hieukol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Hieu_avatar.png', 'KOL'),
       ('Hùng', 'Phạm', 'hungpham@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'hungpham_avatar.jpg', 'KOL'),
       ('Phạm', 'Thoại', 'phamthoai@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'phamthoai_avatar.jpeg', 'KOL'),
       ('Đức', 'Thuận', 'ducthuan@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'ducthuan_avatar.jpg', 'KOL'),
       ('Huỳnh', 'Anh', 'huynhanh@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'huynhanh_avatar.jpg', 'KOL'),
       ('Sa', 'Lý', 'saly@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'saly_avatar.jpeg', 'KOL'),
       ('Tiên', 'KOL', 'tien@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'thitien_avatar.jpeg', 'KOL'),
       ('Ducky', 'KOL', 'ducky@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'ducky_avatar.jpg', 'KOL'),
       ('anhchong', 'congnghe', 'anhchongcongnghe@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'accn_avatar.jpg', 'KOL'),
       ('Mai', 'âm nhạc', 'maiamnhac@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'maiamnhac_avatar.jpg', 'KOL'),
       ('noithatdep', 'kol', 'noithatdep@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'noithatdep_avatar.jpg', 'KOL'),
       ('peoo', 'KOL', 'peoo@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'peoo_avatar.jpg', 'KOL'),
       ('Gnoud', 'KOL', 'gnoud@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'gnoud_avatar.jpg', 'KOL'),
       ('Cô', ' Giáo Quỳnh', 'cgquynh@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'cogiaoquynh_avatar.jpg', 'KOL'),
       ('Thắng', 'Makeup', 'thangmakeup@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'thangmakup_avatar.jpeg', 'KOL'),
       ('Anh', 'Bụng Mỡ', 'anhbungmo@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'anhbungmo_avatar.jpeg', 'KOL'),
       ('Hải', 'Giang', 'haigiang@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'haigiang_avatar.jpg', 'KOL'),
       ('Hoàng', 'Thạch', 'hoangthach@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'hoangthach_avatar.jpg', 'KOL'),
       ('Hà', 'Luật Sư', 'haluatsu@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'luatsuha_avatar.jpg', 'KOL'),
       ('Trung', 'Luật Sư', 'trungluatsu@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'luatsutrung_avatar.png', 'KOL'),
       ('Bình', 'Luật Sư', 'binhluatsu@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'luatsubinh_avatar.jpg', 'KOL'),
       ('Hòa', 'Luật Sư', 'hoaluatsu@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'luatsuhoa_avatar.jpg', 'KOL'),
       ('vtvcpnht', 'Pet', 'vtvcpnht@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'vtvcpnhtpet_avatar.jpeg', 'KOL'),
       ('Mat', 'Pet Family', 'familymatpet@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'familymatpet_avatar.jpg', 'KOL'),
       ('Minn', 'Cookie', 'minn@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'minn_avatar.jpg', 'KOL'),
       ('Tuấn', 'Ngọc', 'tuanngoc@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'tuanngoc_avatar.jpg', 'KOL'),
       ('Ngô', 'Đức Duy', 'ducduy@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'ngoducduy_avatar.jpeg', 'KOL'),
       ('Tùng', 'Nấu Ăn', 'tungnauan@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'tungnauan_avatar.jpg', 'KOL'),
       ('Helu', 'Hí Nè', 'heluhine@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'heluhine_avatar.jpg', 'KOL'),
       ('Neyako ', 'Phạm', 'neyako@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'neyako_avatar.jpg', 'KOL'),
       ('Đặng ', 'Thu Hà', 'thuha@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'thuha_avatar.jpg', 'KOL'),
       ('Admin ', 'Kha', 'adminkha@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'adminkha_avatar.jpg', 'KOL'),
       ('The', 'Anh 28', 'theanh28@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'theanh28_avatar.jpg', 'KOL'),
       ('Tini', 'Entertainment', 'tini@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'tiin_avatar.jpeg', 'KOL'),
       ('Trung', 'Anh', 'tranh@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'tranh_avatar.jpg', 'KOL'),
       ('Góc', 'Setup', 'gocsetup@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'gocsetup_avatar.jpg', 'KOL'),
       ('Ngọc', 'Vương', 'ngocdecor@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'ngocvuong_avatar.jpg', 'KOL'),
       ('Phạm', 'Christian', 'delachris1@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Christian_avatar.jpg', 'KOL'),
       ('Duy', 'Vũ', 'delachris2@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'vuduy_avatar.jpg', 'KOL'),
       ('Gia', 'Bảo', 'delachris3@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'giabao_avatar.jpg', 'KOL'),
       ('Yên', 'Đan', 'yendan@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'yendan_avatar.jpg', 'KOL'),
       ('Hải', 'Đăng', 'haidang@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'haidang_avatar.jpg', 'KOL'),
       ('Minh', 'Mạnh', 'minhmanh@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'minhmanh_avatar.jpeg', 'KOL'),
       ('Lệ', 'Hằng', 'lehang@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'lehang_avatar.jpg', 'KOL'),
       ('Mẹ', 'Rofi', 'merofi@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'merofi_avatar.jpeg', 'KOL');

insert into users(first_name, last_name, email, password, avatar, role)
values ('Sang', 'enterprise', 'sangenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Sang_avatar.png', 'ENTERPRISE'),
       ('Huy', 'enterprise', 'huyenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Huy_avatar.png', 'ENTERPRISE'),
       ('Thắng', 'enterprise', 'thangenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Thang_avatar.png', 'ENTERPRISE'),
       ('Chân', 'enterprise', 'chanenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Chan_avatar.png', 'ENTERPRISE'),
       ('Hiếu', 'enterprise', 'hieuenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Person_Hieu_avatar.png', 'ENTERPRISE'),
       ('Đà Nẵng', 'Beach', 'dnbeach@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'dulichbiendn_avatar.jpg', 'ENTERPRISE'),
       ('Nguyễn', 'Trúc', 'nguyentruc@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'luatssunguyentruc_avatar.jpg', 'ENTERPRISE'),
       ('TN', 'Travel', 'tntravel@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'tranviet_avatar.png', 'ENTERPRISE'),
       ('Thành', 'Hưng', 'thanhhung@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'thanhhung_avatar.jpg', 'ENTERPRISE'),
       ('Quang', 'Trung', 'quangtrung@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'quangtrung_avatar.jpg', 'ENTERPRISE'),
       ('Khát', 'Vọng Xanh', 'khatvongxanh@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'khatvongxanh_avatar.png', 'ENTERPRISE'),
       ('M', 'House', 'mhouse@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'Mhouse_avatar.jpg', 'ENTERPRISE'),
       ('CP', 'Acecook', 'acecook@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'acecook_avatar.png', 'ENTERPRISE'),
       ('Matrix', 'TNHH', 'matrix@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'matrix_avatar.png', 'ENTERPRISE'),
       ('Naunau', 'Beauti', 'naunau@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'naunaua_avatar.jpg', 'ENTERPRISE'),
       ('Sao', 'Thái Dương', 'saothaiduong@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'saothaiduong_avatar.jpg', 'ENTERPRISE'),
       ('Hương Thị', 'Traditional ', 'huongthi@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'viethuong_avatar.jpg', 'ENTERPRISE'),
       ('Hani', 'Cosmetic', 'hani@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'hani_avatar.jpg', 'ENTERPRISE'),
       ('Yody', 'Fashion', 'yody@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'yody_avatar.jpg', 'ENTERPRISE'),
       ('Nowsaigon', 'Clothing', 'nowsaigon@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'nowsaigon_avatar.png', 'ENTERPRISE'),
       ('Elise', 'Fashion', 'elise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'elise_avatar.jpg', 'ENTERPRISE'),
       ('Ivy', 'Moda', 'ivy@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'ivy_avatar.jpg', 'ENTERPRISE'),
       ('An', 'Phước', 'anphuoc@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'anphuoc_avatar.jpg', 'ENTERPRISE'),
       ('Phạm Bình', 'Education', 'phambinh@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'phambinh_avatar.png', 'ENTERPRISE'),
       ('Royal', 'School', 'royalschool@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'hoanggia_avatar.png', 'ENTERPRISE'),
       ('Gic', 'Education', 'Giceducation@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'gic_avatar.jpg', 'ENTERPRISE'),
       ('Happy', 'Life', 'happylife@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'happylife_avatar.jpg', 'ENTERPRISE'),
       ('Ah', 'Global', 'ahglobal@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'global_avatar.jpg', 'ENTERPRISE'),
       ('Xuân Huy', 'Decor', 'xuanhuydecor@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'xuanhuy_avatar.jpg', 'ENTERPRISE'),
       ('TNHH', 'Trung Giang', 'trunggiangtnhh@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'trunggiang_avatar.jpg', 'ENTERPRISE'),
       ('Thịnh Phú', 'Pharmaceutical', 'thinhphu@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'thienthinhphu_avatar.jpeg', 'ENTERPRISE'),
       ('Phụng Hoàng', 'Real Estate', 'phunghoang@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'phunghoang_avatar.png', 'ENTERPRISE'),
       ('Danh Sơn', 'Group', 'danhson@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'danhson_avatar.jpg', 'ENTERPRISE'),
       ('New', 'Star', 'newstar@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'newstar_avatar.jpg', 'ENTERPRISE'),
       ('Việt Thành', 'Technology', 'vietthanh@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'thanhviet_avatar.jpg', 'ENTERPRISE'),
       ('Danago', 'Travel', 'danago@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'danago_avatar.png', 'ENTERPRISE'),
       ('Green', 'Tour', 'greentour@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'greentour_avatar.png', 'ENTERPRISE'),
       ('Sài Gòn', 'Tourist', 'sgtourist@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'saigontourist_avatar.png', 'ENTERPRISE'),
       ('K', 'Beauti', 'kbeauti@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'thammyvienk_avatar.png', 'ENTERPRISE'),
       ('Hưng Thịnh', 'design', 'hungthinh@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'hungthinh_avatar.png', 'ENTERPRISE'),
       ('Minh San', 'Travel', 'minhsan@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'minhsan_avatar.jpg', 'ENTERPRISE'),
       ('Tri', 'Thức Việt', 'trithucviet@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'trithucviet_avatar.png', 'ENTERPRISE'),
       ('Sendy', 'Spa', 'sendy@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'sendi_avatar.jpg', 'ENTERPRISE'),
       ('Trường Gia', 'Hotel', 'truonggia@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'truonggia_avatar.jpg', 'ENTERPRISE'),
       ('Tago', 'Easy', 'tago@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', 'tago_avatar.png', 'ENTERPRISE');