insert into fields(name, type)
values ('Làm Đẹp (Beauty)', 'KOL'),
       ('Ẩm Thực (Food)', 'KOL'),
       ('Du Lịch (Travel)', 'KOL'),
       ('Thể Thao (Sport)', 'KOL'),
       ('Đời Sống (Life Style)', 'KOL'),
       ('Thời Trang (Fashion)', 'KOL'),
       ('Sức Khoẻ (Health)', 'KOL'),
       ('Công Nghệ (Tech)', 'KOL'),
       ('Giải Trí (Entertainment)', 'KOL'),
       ('Tài chính (Finance)', 'KOL'),
       ('Thú Cưng (Pet)', 'KOL'),
       ('Nội Thất (Interior)', 'KOL'),
       ('Pháp Lý (Juridical)', 'KOL'),
       ('Bất Động Sản (Real Estate)', 'KOL'),
       ('khách Sạn (Hotel)', 'KOL'),
       ('Sách (Book)', 'KOL'),
       ('Thiết Kế (Design)', 'KOL'),
       ('Đồ Gia Dụng (Houseware)', 'KOL'),
       ('Nông Nghiệp và Khai Thác', 'ENTERPRISE'),
       ('Thông Tin', 'ENTERPRISE'),
       ('Vận Tải', 'ENTERPRISE'),
       ('Dịch Vụ Tài Chính', 'ENTERPRISE'),
       ('Bất động sản', 'ENTERPRISE'),
       ('Bán Lẻ và Phân Phối', 'ENTERPRISE'),
       ('Thương Mại Điện Tử', 'ENTERPRISE'),
       ('Công Nghệ Thông Tin', 'ENTERPRISE'),
       ('Y Tế', 'ENTERPRISE'),
       ('Giáo Dục', 'ENTERPRISE'),
       ('Du Lịch', 'ENTERPRISE');
