insert into cities(id, name, code)
values (1, 'An Giang', 'AG'),
       (2, 'Bà Rịa - Vũng Tàu', 'BRVT'),
       (3, 'Bắc Giang', 'BG'),
       (4, 'Bắc Kạn', 'BK'),
       (5, 'Bạc Liêu', 'BL'),
       (6, 'Bắc Ninh', 'BN'),
       (7, 'Bến Tre', 'BT'),
       (8, 'Bình Định', 'BĐ'),
       (9, 'Bình Dương', 'BD'),
       (10, 'Bình Phước', 'BP'),
       (11, 'Bình Thuận', 'BTh'),
       (12, 'Cà Mau', 'CM'),
       (13, 'Cần Thơ', 'CT*'),
       (14, 'Cao Bằng', 'CB'),
       (15, 'Đà Nẵng', 'ĐN*'),
       (16, 'Đắk Lắk', 'ĐL'),
       (17, 'Đắk Nông', 'ĐN'),
       (18, 'Điện Biên', 'ĐB'),
       (19, 'Đồng Nai', 'ĐNai'),
       (20, 'Đồng Tháp', 'ĐT'),
       (21, 'Gia Lai', 'GL'),
       (22, 'Hà Giang', 'HG'),
       (23, 'Hà Nam', 'HN'),
       (24, 'Hà Nội', 'HN*'),
       (25, 'Hà Tĩnh', 'HT'),
       (26, 'Hải Dương', 'HĐ'),
       (27, 'Hải Phòng', 'HP*'),
       (28, 'Hậu Giang', 'HGi'),
       (29, 'Hoà Bình', 'HB'),
       (30, 'Hưng Yên', 'HY'),
       (31, 'Khánh Hòa', 'KH'),
       (32, 'Kiên Giang', 'KG'),
       (33, 'Kon Tum', 'KT'),
       (34, 'Lai Châu', 'LC'),
       (35, 'Lâm Đồng', 'LD'),
       (36, 'Lạng Sơn', 'LS'),
       (37, 'Lào Cai', 'LCai'),
       (38, 'Long An', 'LA'),
       (39, 'Nam Định', 'NĐi'),
       (40, 'Nghệ An', 'NA'),
       (41, 'Ninh Bình', 'NB'),
       (42, 'Ninh Thuận', 'NT'),
       (43, 'Phú Thọ', 'PT'),
       (44, 'Phú Yên', 'PY'),
       (45, 'Quảng Bình', 'QB'),
       (46, 'Quảng Nam', 'QNam'),
       (47, 'Quảng Ngãi', 'QNg'),
       (48, 'Quảng Ninh', 'QN'),
       (49, 'Quảng Trị', 'QT'),
       (50, 'Sóc Trăng', 'ST'),
       (51, 'Sơn La', 'SL'),
       (52, 'Tây Ninh', 'TN'),
       (53, 'Thái Bình', 'TB'),
       (54, 'Thái Nguyên', 'TNg'),
       (55, 'Thanh Hóa', 'TH'),
       (56, 'Thừa Thiên Huế', 'TTH'),
       (57, 'Tiền Giang', 'TG'),
       (58, 'Thành phố Hồ Chí Minh', 'HCM*'),
       (59, 'Trà Vinh', 'TV'),
       (60, 'Tuyên Quang', 'TQ'),
       (61, 'Vĩnh Long', 'VL'),
       (62, 'Vĩnh Phúc', 'VP'),
       (63, 'Yên Bái', 'YB');

insert into fields(name, type)
values ('Làm Đẹp (Beauty)', 'KOL'),
       ('Ẩm Thực (Food)', 'KOL'),
       ('Du Lịch (Travel)', 'KOL'),
       ('Thể Thao (Sport)', 'KOL'),
       ('Đời Sống (Life Style)', 'KOL'),
       ('Thời Trang (Fashion)', 'KOL'),
       ('Sức Khoẻ (Health)', 'KOL'),
       ('Công Nghệ (Tech)', 'KOL'),
       ('Giải Trí (Entertainment)', 'KOL'),
       ('Nông Nghiệp và Khai Thác', 'ENTERPRISE'),
       ('Thông Tin', 'ENTERPRISE'),
       ('Vận Tải', 'ENTERPRISE'),
       ('Dịch Vụ Tài Chính', 'ENTERPRISE'),
       ('Bất động sản', 'ENTERPRISE'),
       ('Bán Lẻ và Phân Phối', 'ENTERPRISE'),
       ('Thương Mại Điện Tử', 'ENTERPRISE'),
       ('Công Nghệ Thông Tin', 'ENTERPRISE'),
       ('Y Tế', 'ENTERPRISE'),
       ('Giáo Dục', 'ENTERPRISE'),
       ('Du Lịch', 'ENTERPRISE');

insert into users(first_name, last_name, email, password, avatar, role)
values ('admin', 'admin', 'admin@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'ADMIN');

insert into users(first_name, last_name, email, password, avatar, role)
values ('sang', 'kol', 'sangkol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'KOL'),
       ('huy', 'kol', 'huykol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'KOL'),
       ('thang', 'kol', 'thangkol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'KOL'),
       ('chan', 'kol', 'chankol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'KOL'),
       ('hieu', 'kol', 'hieukol@kolgo.com', '$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'KOL');

insert into kols (user_id, gender, phone, post_price, video_price, facebook_url, instagram_url, tiktok_url, youtube_url)
values (2, 'MALE', '0123456789', 500000, 10000000, 'https://facebook.com/sangkol', 'https://instagram.com/sangkol', 'https://tiktok.com/sangkol', 'https://youtube.com/sangkol'),
       (3, 'FEMALE', '0123456789', 300000, 500000, 'https://facebook.com/sangkol', 'https://instagram.com/huykol', 'https://tiktok.com/huykol', 'https://youtube.com/huykol'),
       (4, 'MALE', '0123456789', 100000, 300000, 'https://facebook.com/sangkol', 'https://instagram.com/thangkol', 'https://tiktok.com/thangkol', 'https://youtube.com/thangkol'),
       (5, 'FEMALE', '0123456789', 50000, 100000, 'https://facebook.com/sangkol', 'https://instagram.com/chankol', 'https://tiktok.com/chankol', 'https://youtube.com/chankol'),
       (6, 'FEMALE', '0123456789', 30000, 50000, 'https://facebook.com/sangkol', 'https://instagram.com/hieukol', 'https://tiktok.com/hieukol', 'https://youtube.com/hieukol');

insert into users(first_name, last_name, email, password, avatar, role)
values ('sang', 'enterprise', 'sangenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'ENTERPRISE'),
       ('huy', 'enterprise', 'huyenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'ENTERPRISE'),
       ('thang', 'enterprise', 'thangenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'ENTERPRISE'),
       ('chan', 'enterprise', 'chanenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'ENTERPRISE'),
       ('hieu', 'enterprise', 'hieuenterprise@kolgo.com','$2a$10$4zkmuZDURkxgJBmH8g2JyOF6U6oczpJBKLQ2iFQdlf1zpD.cCFqLa', null, 'ENTERPRISE');

insert into enterprises(user_id, name, phone, tax_id)
values (7, 'Công ty TNHH 1 thành viên Sang Đỗ', '0123456789','3216549873216'),
       (8, 'Công ty TNHH 1 thành viên Huy Trần', '0123456789', '1234567891234'),
       (9, 'Công ty TNHH 1 thành viên Thắng Trần', '0123456789', '9876543219876'),
       (10, 'Công ty TNHH 1 thành viên Chân Phạm', '0123456789', '7894561237894'),
       (11, 'Công ty TNHH 1 thành viên Hiếu Văn', '0123456789', '6549873216549');
